### ISSUE TITLE
App listing not shown when MetaMask is locked

### ISSUE THREAD

**Issue by Diti** [DigitalPenguins/dapp-election#1]
Steps to reproduce:

1. Have at least one candidate in the list
2. Have the election closed(?)
3. **Have MetaMask locked**

The list of candidates shows up empty, and the JS console says `Error: [ethjs-abi] while encoding address, invalid address value, not alphanumeric 20 byte hex string`.

**Comment by LucSalommez** [comment]
The bug is now fixed.
We were previously checking if the user could vote to show him the list of candidates.
It is now only checked in order to know if the "Vote" button should be enabled or not.
